### PR TITLE
Operation CI cleanup

### PR DESCRIPTION
**Pull request by msheiny**
Ready to go.

Adding in circle CI, swapped kvm/vagrant for docker.

### CODE REVIEW

**Comment by msheiny** [comment]
@conorsch ping. take your time buddy - no rush

**Comment by conorsch** [comment]
Reviewing!

**Comment by msheiny** [comment]
FYI - forgot to mention ya need to do the `grsec-chroot-toggle` dance to spin up a local instance

**Comment by conorsch** [comment]
I have several times now gotten this error:

```
    TASK [geerlingguy.jenkins : Install Jenkins plugins using password.] ***********
    failed: [jenkins_config_debian] (item=github) => {"changed": false, "details": "Connection failure: timed out", "item": "github", "msg": "Cannot install plugin."}
    changed: [jenkins_config_debian] => (item=github-branch-source)
    changed: [jenkins_config_debian] => (item=job-dsl)
    changed: [jenkins_config_debian] => (item=simple-theme-plugin)
    changed: [jenkins_config_debian] => (item=ssh-credentials)

    failed: [jenkins_config_debian] (item=workflow-aggregator) => {"changed": false, "details": "Connection failure: timed out", "item": "workflow-aggregator", "msg": "Cannot install plugin."}
```

However, since that's a dependency role, it shouldn't block merge here. Plus, CI is passing just fine.

**Comment by msheiny** [comment]
yeah @conorsch -- i also saw that.... I think thats unfortunately an upstream issue with the plugin used by geerlingguy.jenkins which is the official ansible module --> http://docs.ansible.com/ansible/latest/jenkins_plugin_module.html . I wonder if expanding `jenkins_plugin_timeout: 60` even higher makes it work.

**Pull request merged**
